title: Garrett Wong
description: Stuff that I come across and find interesting.
author: Garrett Wong
email: garrettwong99@gmail.com
phone: (510)-857-3823
github: https://github.com/garrettwong99
about: 
disqus_shortname: programming
google_analytics: UA-31048387-6
avatar_url: /static/img/me.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/garrett.wong.39"
    - icon: fa-twitter
      link: "https://twitter.com/garrettwong99"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/garrett-w-542b74132/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/garrettwong99"

share:
  twitter_username: garrettwong99
  # fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blogs
      url: /blogs/
    - text: XML Feed
      url: /feed.xml
# url: "http://localhost:4000"
url: "https://garrettwong99.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/blogs/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
